### ISSUE TITLE
Товары

### ISSUE THREAD

**Issue by milkina** [shcherbinina-yelyzaveta/projects#10]
Сортировка должны быть по цене или рейтингу или имени. То есть пишите три разных компаратора.

**Comment by shcherbinina-yelyzaveta** [comment]
исправлено

**Comment by milkina** [comment]
Вместо
return p1.getRating() < p2.getRating() ? -1 : 1; 
можно проще:
return p1.getRating() - p2.getRating() ;

**Comment by shcherbinina-yelyzaveta** [comment]
исправлено
