### ISSUE TITLE
Lesson 8. Matrix

### ISSUE THREAD

**Issue by milkina** [shcherbinina-yelyzaveta/projects#2]
1.  В конструкторе  Matrix(double[][] matrix)  можно просто
 this.matrix = matrix;
2. Метод sum - используйте short-circuit &&.
3. Метод in - hasNextInt указывайте для каждого вызова nextInt.

**Comment by milkina** [comment]
Done. Но  можно еще вынести в отдельный метод
 if (scanner.hasNextInt()) {
                        n = scanner.nextInt();
                    } else {
                        System.out.println("Input Error!");
                    }

**Comment by shcherbinina-yelyzaveta** [comment]
Исправлено
