### ISSUE TITLE
Student -Aspirant

### ISSUE THREAD

**Issue by milkina** [shcherbinina-yelyzaveta/projects#5]
1. StudentAspirantMain - неотформатировно.
2.    System.out.println(smb.toString());  -метод toString не надо явно вызывать, можно просто
   System.out.println(smb);
3.  public Aspirant() {
        super();
        this.scientificWork = "scientific work";
    } - вызов super не обязательный. JVM его и так добавит.

**Comment by shcherbinina-yelyzaveta** [comment]
Исправлено
